# frozen_string_literal: true

require 'yaml'
require 'date'
require 'terminal-table'
require 'colorize'
require 'i18n'
require 'bcrypt'
require_relative 'locale_setter'
require_relative '../app'
require_relative '../app/controllers/application_controller'
require_relative '../app/controllers/session_controller'
require_relative '../app/controllers/users_controller'
require_relative '../app/controllers/users_searchs_controller'
require_relative '../app/models/application_record'
require_relative '../app/models/user'
require_relative '../app/models/user_searchs'
require_relative '../app/statistics_manager'
require_relative '../app/cars_searcher'
require_relative '../app/input_collector'
require_relative '../app/main_menu'
require_relative '../app/output_manager'
require_relative '../app/sorting_manager'
require_relative '../app/show_cars'
require_relative '../lib/database'
